model_list:

  - model_name: litellm-gemini
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GEMINI_API_KEY

  - model_name: "my-sample-llm"
    litellm_params:
      model: "my-llm/xyz"

litellm_settings:
  custom_provider_map:
  - {"provider": "my-llm", "custom_handler": my_ai.my_llm}